### PR TITLE
Hashmap Problems

### PR DESCRIPTION
**Pull request by adityasunny1189**
All of the hashmap Problems

### CODE REVIEW

**Comment by priyanshisharma** [comment]
Which problem is this?

**Comment by priyanshisharma** [comment]
Which hashmap problems are you referring to @adityasunny1189 ?

**Comment by adityasunny1189** [comment]
> Which hashmap problems are you referring to @adityasunny1189 ?

The problems I have mentioned in my code only at the top

**Comment by priyanshisharma** [comment]
I don't think i was looking forward to these and so closing this. Please refer #1 and #54 comment in case of any doubts.

**Pull request closed without merging**
