### PR TITLE
 sept_29_word break.cpp

### PR DESCRIPTION
**Pull request by shibrahmachari**

### CODE REVIEW

**Review by priyanshisharma — CHANGES_REQUESTED** [review]
I don't think I was looking for a solution to this problem, please check #1 , but if I do open this problem for PRs I will definitely check this first, thanks for your time and effort! ✨

Please add appropriate file extension i.e. `.cpp` to the file name.

**Comment by priyanshisharma** [comment]
@shibrahmachari I've chosen to open this problem for PR as well, so please add the file extension so that I could merge this.

**Review by shibrahmachari — COMMENTED** [review]
Done

**Review by priyanshisharma — APPROVED** [review]
Awesome 🚀

**Pull request merged**
