### PR TITLE
created april folder and added april 17 and 24 codes

### PR DESCRIPTION
**Pull request by Deepak290701**
This PR is for the problems assigned to me in issue #54 .

### CODE REVIEW

**Comment by Deepak290701** [comment]
@priyanshisharma  can you please check the PR and also can you please check this
Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

It is being shown for the PR that I made in your repo.

**Comment by priyanshisharma** [comment]
I have added the hacktoberfest topic a while ago, can you please crosscheck?
Screen Shot 2020-10-04 at 4 41 01 PM

**Review by priyanshisharma — APPROVED** [review]
Looks perfect 🚀 Merging this 🔥

**Comment by Deepak290701** [comment]
@priyanshisharma  yes now the PR is in review stage thanks for adding the tag .

**Pull request merged**
