### PR TITLE
added day 30 cpp solution

### PR DESCRIPTION
**Pull request by yogyasinghal**

### CODE REVIEW

**Review by priyanshisharma — COMMENTED** [review]
I don't think I was looking for a solution to this (please check #1 ), but if I do I will definitely merge this. Thanks for your time and effort!

**Comment by yogyasinghal** [comment]
Okk so it will count in my hacktoberfest Or not? Any idea?

**Comment by priyanshisharma** [comment]
I'm sorry I don't have much idea about that @yogyasinghal

**Review by priyanshisharma — APPROVED** [review]
Beats 83.32% 🔥 Merging this 🚀 
PS- Now that I've merged this, I'm certain it should count for Hacktoberfest too.

**Comment by yogyasinghal** [comment]
Thanks

**Pull request merged**
