### PR TITLE
Added August_31_delete-node-in-a-bst.cpp solution in August folder

### PR DESCRIPTION
**Pull request by singhalpranav22**
# Added 31 Aug LeetCode solution
___
### Contribution for Hacktober fest

### CODE REVIEW

**Review by priyanshisharma — COMMENTED** [review]
This has been claimed by @gayatri517 in #1 and she has also been working on it in #19 . If she isn't able to make the requisite modification, i'll consider merging this. thanks for your time and effort!

**Comment by singhalpranav22** [comment]
Ok can i do some other question ?

**Comment by priyanshisharma** [comment]
Unfortunately, I haven't opened any more questions for solving right now, but I'll definitely update on 7th October regarding this.

**Comment by priyanshisharma** [comment]
sInce #19 has merged, I'm closing this.

**Pull request closed without merging**
