### PR TITLE
Sept_12_ Combination Sum  III.cpp

### PR DESCRIPTION
**Pull request by shibrahmachari**

### CODE REVIEW

**Review by priyanshisharma — CHANGES_REQUESTED** [review]
First of all, kudos for coming up with a solution that beats 100% 🔥 
* This problem was taken up by @ojas032 in #1 so if he doesn't make a PR soon I'll merge this.
* Please give file its appropriate file extension.

**Review by shibrahmachari — COMMENTED** [review]
added the extension.

**Comment by priyanshisharma** [comment]
@shibrahmachari please add it to your file name. You just changed the title of the PR.

**Review by shibrahmachari — COMMENTED** [review]
done

**Comment by priyanshisharma** [comment]
Thanks, but since @ojas032 had claimed it first and has also solved it in #27 , I'll need to close this. Thanks for your time and efforts ✨

**Pull request closed without merging**
