### PR TITLE
Leetcode question August 25th

### PR DESCRIPTION
**Pull request by sai-pothuri**

### CODE REVIEW

**Review by priyanshisharma — CHANGES_REQUESTED** [review]
Please debug this
Screen Shot 2020-10-01 at 2 16 21 PM

**Comment by sai-pothuri** [comment]
Yes I'll update it soon

**Comment by sai-pothuri** [comment]
It should work now if i'm not wrong

**Review by priyanshisharma — CHANGES_REQUESTED** [review]
Screen Shot 2020-10-02 at 2 56 51 AM
This is the problem header
```

class Solution(object):
    def fizzBuzz(self, n):
        """
        :type n: int
        :rtype: List[str]
        """

```

**Comment by sai-pothuri** [comment]
The code i wrote is for python 3. I think you're running it in python 2 or earlier versions. There was an update in python 3 where you can specify the type of the parameter like i did in my code. But if you want me to change it to the python 2 version, let me know:)
I don't think there's any other problems but if there are, do let me know.

**Review by priyanshisharma — APPROVED** [review]
yeah my bad, it works in Python3. I don't really practice in Python so didn't have as much of an idea. Sorry for the inconvenience and thanks for letting me know, merging this 🚀 🚀

**Comment by sai-pothuri** [comment]
Haha it's nothing to apologize for XD
Thank you for creating an interesting issue:)

**Pull request merged**
